# Generated by Django 4.1.4 on 2023-01-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
