# Generated by Django 4.1.4 on 2023-01-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pqrsdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pqrsdf', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('type_pqrsdf', models.CharField(choices=[('Peticion', 'Petición'), ('Queja', 'Queja/Reclamo'), ('Solicitud', 'Solicitud de información'), ('Denuncia', 'Denuncia'), ('Sugerencia', 'Sugerencia/Propuesta')], max_length=10, verbose_name='Tipo de PQRSDF')),
                ('type_anonymous', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('type_identification', models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('NU', 'NUIP'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PS', 'Pasaporte')], max_length=3, null=True, verbose_name='Tipo de identificación')),
                ('identification', models.CharField(blank=True, max_length=30, null=True, verbose_name='Identificación')),
                ('medium_contact', models.CharField(blank=True, choices=[('CE', 'Correo electrónico'), ('DC', 'Dirección de correspondencia')], max_length=2, null=True, verbose_name='Medio de contacto')),
                ('number_contact', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de contacto')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
        ),
    ]
