# Generated by Django 4.1.4 on 2023-01-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqrsdf',
            options={'verbose_name': 'Pqrsdf', 'verbose_name_plural': 'Pqrsdf'},
        ),
    ]
