# Generated by Django 4.1.5 on 2023-04-20 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pqrsdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqrsdf',
            options={'verbose_name': 'Pqrsdf', 'verbose_name_plural': 'Pqrsdf'},
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='correspondence_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de correspondencia'),
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='days_passed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo transcurrido'),
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='municipality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Municipio / Distrito'),
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Barrio / Vereda / Corregimiento'),
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='radicated',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Radicado'),
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='state_actual',
            field=models.IntegerField(choices=[(1, 'Radicación'), (2, 'Elaboración'), (3, 'Revisión'), (4, 'Finalizado')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='date_pqrsdf',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='medium_contact',
            field=models.IntegerField(blank=True, choices=[(1, 'Correo electrónico'), (2, 'Dirección de correspondencia')], null=True, verbose_name='Medio de contacto'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='type_anonymous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='type_identification',
            field=models.IntegerField(blank=True, choices=[(1, 'Cédula de ciudadanía'), (2, 'NUIP'), (3, 'Cédula de extranjería'), (4, 'NIT'), (5, 'Pasaporte')], null=True, verbose_name='Tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='type_pqrsdf',
            field=models.IntegerField(choices=[(1, 'Petición'), (2, 'Queja/Reclamo'), (3, 'Solicitud de información'), (4, 'Denuncia'), (5, 'Sugerencia/Propuesta')], verbose_name='Tipo de PQRSDF'),
        ),
        migrations.CreateModel(
            name='ResponsePqrsdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(blank=True)),
                ('pqrsdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrsdf.pqrsdf', verbose_name='Respuesta')),
                ('user_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
        migrations.CreateModel(
            name='PqrsdfState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Radicación'), (2, 'Elaboración'), (3, 'Revisión'), (4, 'Finalizado')], default=1)),
                ('date_previous_change', models.DateTimeField(null=True, verbose_name='Fecha anterior')),
                ('date_change', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actual')),
                ('id_pqrsdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrsdf.pqrsdf', verbose_name='Id pqrsdf')),
                ('user_change', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_change', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Actual')),
                ('user_previous_change', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_previous_change', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Anterior')),
            ],
            options={
                'verbose_name': 'PqrsdfState',
                'verbose_name_plural': 'PqrsdfStates',
            },
        ),
    ]
