# Generated by Django 4.1.5 on 2023-04-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0002_alter_pqrsdf_options_pqrsdf_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PqrsdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pqrsdf_files/')),
                ('pqrsdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrsdf.pqrsdf')),
            ],
            options={
                'verbose_name': 'PqrsdfFile',
                'verbose_name_plural': 'PqrsdfFile',
            },
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pqrsdf_files', to='pqrsdf.pqrsdffile', verbose_name='Adjunto'),
        ),
    ]
