# Generated by Django 4.1.4 on 2023-01-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0003_state_pqrsdfstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pqrsdfstate',
            old_name='date_out',
            new_name='date_output',
        ),
    ]
