# Generated by Django 4.1.4 on 2023-01-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0004_rename_date_out_pqrsdfstate_date_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsdf',
            name='date_pqrsdf',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
