# Generated by Django 4.1.4 on 2023-01-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0006_pqrsdf_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrsdf',
            name='correspondence_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de correspondencia'),
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='municipality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Municipio / Distrito'),
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Barrio / Vereda / Corregimiento'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='type_anonymous',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
