# Generated by Django 4.1.4 on 2023-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0007_pqrsdf_correspondence_address_pqrsdf_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsdf',
            name='medium_contact',
            field=models.CharField(blank=True, choices=[('1', 'Correo electrónico'), ('2', 'Dirección de correspondencia')], max_length=2, null=True, verbose_name='Medio de contacto'),
        ),
    ]
