# Generated by Django 4.1.4 on 2023-01-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0008_alter_pqrsdf_medium_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsdf',
            name='type_identification',
            field=models.CharField(blank=True, choices=[('1', 'Cédula de ciudadanía'), ('2', 'NUIP'), ('3', 'Cédula de extranjería'), ('4', 'NIT'), ('5', 'Pasaporte')], max_length=3, null=True, verbose_name='Tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='type_pqrsdf',
            field=models.CharField(choices=[('1', 'Petición'), ('2', 'Queja/Reclamo'), ('3', 'Solicitud de información'), ('4', 'Denuncia'), ('5', 'Sugerencia/Propuesta')], max_length=10, verbose_name='Tipo de PQRSDF'),
        ),
    ]
