# Generated by Django 4.1.4 on 2023-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0009_alter_pqrsdf_type_identification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqrsdfstate',
            name='id_state',
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='state',
            field=models.CharField(choices=[('filing', 'Radicación'), ('elaboration', 'Elaboración'), ('revision', 'Revisión'), ('finalized', 'Finalizado')], default='filing', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='medium_contact',
            field=models.CharField(blank=True, choices=[('CE', 'Correo electrónico'), ('DC', 'Dirección de correspondencia')], max_length=2, null=True, verbose_name='Medio de contacto'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='type_identification',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('NU', 'NUIP'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PS', 'Pasaporte')], max_length=3, null=True, verbose_name='Tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='type_pqrsdf',
            field=models.CharField(choices=[('Peticion', 'Petición'), ('Queja', 'Queja/Reclamo'), ('Solicitud', 'Solicitud de información'), ('Denuncia', 'Denuncia'), ('Sugerencia', 'Sugerencia/Propuesta')], max_length=10, verbose_name='Tipo de PQRSDF'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
