# Generated by Django 4.1.4 on 2023-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0010_remove_pqrsdfstate_id_state_pqrsdf_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsdf',
            name='state',
            field=models.CharField(choices=[('Radicacion', 'Radicación'), ('Elaboracion', 'Elaboración'), ('Revision', 'Revisión'), ('Finalizado', 'Finalizado')], default='filing', max_length=100, verbose_name='Estado'),
        ),
    ]
