# Generated by Django 4.1.4 on 2023-01-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0011_alter_pqrsdf_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsdf',
            name='state',
            field=models.CharField(choices=[('Radicacion', 'Radicación'), ('Elaboracion', 'Elaboración'), ('Revision', 'Revisión'), ('Finalizado', 'Finalizado')], default='Radicacion', max_length=100, verbose_name='Estado'),
        ),
    ]
