# Generated by Django 4.1.4 on 2023-01-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0012_alter_pqrsdf_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrsdf',
            name='radicated',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Radicado'),
        ),
    ]
