# Generated by Django 4.1.4 on 2023-01-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0014_pqrsdfstate_id_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PqrsdfState',
        ),
    ]
