# Generated by Django 4.1.4 on 2023-01-24 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pqrsdf', '0015_delete_pqrsdfstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PqrsdfState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_input', models.DateField(blank=True, null=True, verbose_name='Fecha Entrada')),
                ('date_output', models.DateField(blank=True, null=True, verbose_name='Fecha Salida')),
                ('user_change_input', models.CharField(blank=True, max_length=191, null=True, verbose_name='Usuario entrada')),
                ('user_change_output', models.CharField(blank=True, max_length=10, null=True, verbose_name='Usuario Salida')),
                ('id_pqrsdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pqrsdf.pqrsdf')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PqrsdfState',
                'verbose_name_plural': 'PqrsdfStates',
            },
        ),
    ]
