# Generated by Django 4.1.4 on 2023-01-24 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pqrsdf', '0017_remove_pqrsdfstate_id_pqrsdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pqrsdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('radicated', models.CharField(blank=True, max_length=50, null=True, verbose_name='Radicado')),
                ('date_pqrsdf', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('state', models.CharField(choices=[('Radicacion', 'Radicación'), ('Elaboracion', 'Elaboración'), ('Revision', 'Revisión'), ('Finalizado', 'Finalizado')], default='Radicacion', max_length=100, verbose_name='Estado')),
                ('type_pqrsdf', models.CharField(choices=[('Peticion', 'Petición'), ('Queja', 'Queja/Reclamo'), ('Solicitud', 'Solicitud de información'), ('Denuncia', 'Denuncia'), ('Sugerencia', 'Sugerencia/Propuesta')], max_length=10, verbose_name='Tipo de PQRSDF')),
                ('type_anonymous', models.BooleanField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('type_identification', models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('NU', 'NUIP'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PS', 'Pasaporte')], max_length=3, null=True, verbose_name='Tipo de identificación')),
                ('identification', models.CharField(blank=True, max_length=30, null=True, verbose_name='Identificación')),
                ('medium_contact', models.CharField(blank=True, choices=[('CE', 'Correo electrónico'), ('DC', 'Dirección de correspondencia')], max_length=2, null=True, verbose_name='Medio de contacto')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correo electrónico')),
                ('correspondence_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de correspondencia')),
                ('neighborhood', models.CharField(blank=True, max_length=200, null=True, verbose_name='Barrio / Vereda / Corregimiento')),
                ('municipality', models.CharField(blank=True, max_length=200, null=True, verbose_name='Municipio / Distrito')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='País')),
                ('number_contact', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de contacto')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Pqrsdf',
                'verbose_name_plural': 'Pqrsdf',
            },
        ),
        migrations.CreateModel(
            name='PqrsdfState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_input', models.DateField(blank=True, null=True, verbose_name='Fecha Entrada')),
                ('date_output', models.DateField(blank=True, null=True, verbose_name='Fecha Salida')),
                ('user_change_input', models.CharField(blank=True, max_length=191, null=True, verbose_name='Usuario entrada')),
                ('user_change_output', models.CharField(blank=True, max_length=10, null=True, verbose_name='Usuario Salida')),
                ('id_pqrsdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pqrsdf.pqrsdf')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PqrsdfState',
                'verbose_name_plural': 'PqrsdfStates',
            },
        ),
    ]
