# Generated by Django 4.1.4 on 2023-01-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0018_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsdfstate',
            name='id_user',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
