# Generated by Django 4.1.4 on 2023-01-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0019_alter_pqrsdfstate_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqrsdfstate',
            name='id_user',
        ),
        migrations.AlterField(
            model_name='pqrsdfstate',
            name='date_input',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Entrada'),
        ),
        migrations.AlterField(
            model_name='pqrsdfstate',
            name='date_output',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Salida'),
        ),
    ]
