# Generated by Django 4.1.5 on 2023-03-16 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pqrsdf', '0020_remove_pqrsdfstate_id_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqrsdf',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pqrsdfstate',
            name='date_input',
        ),
        migrations.RemoveField(
            model_name='pqrsdfstate',
            name='date_output',
        ),
        migrations.RemoveField(
            model_name='pqrsdfstate',
            name='user_change_input',
        ),
        migrations.RemoveField(
            model_name='pqrsdfstate',
            name='user_change_output',
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='state_actual',
            field=models.IntegerField(choices=[(1, 'Radicación'), (2, 'Elaboración'), (3, 'Revisión'), (4, 'Finalizado')], default=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='pqrsdfstate',
            name='date_change',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Estado'),
        ),
        migrations.AddField(
            model_name='pqrsdfstate',
            name='state',
            field=models.CharField(choices=[(1, 'Radicación'), (2, 'Elaboración'), (3, 'Revisión'), (4, 'Finalizado')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='pqrsdfstate',
            name='user_change',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='medium_contact',
            field=models.IntegerField(blank=True, choices=[(1, 'Correo electrónico'), (2, 'Dirección de correspondencia')], null=True, verbose_name='Medio de contacto'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='type_identification',
            field=models.IntegerField(blank=True, choices=[(1, 'Cédula de ciudadanía'), (2, 'NUIP'), (3, 'Cédula de extranjería'), (4, 'NIT'), (5, 'Pasaporte')], null=True, verbose_name='Tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='type_pqrsdf',
            field=models.IntegerField(choices=[(1, 'Petición'), (2, 'Queja/Reclamo'), (3, 'Solicitud de información'), (4, 'Denuncia'), (5, 'Sugerencia/Propuesta')], verbose_name='Tipo de PQRSDF'),
        ),
        migrations.AlterField(
            model_name='pqrsdfstate',
            name='id_pqrsdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrsdf.pqrsdf', verbose_name='Historial Estados'),
        ),
        migrations.CreateModel(
            name='ResponsePqrsdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(blank=True)),
                ('pqrsdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrsdf.pqrsdf', verbose_name='Respuesta')),
                ('user_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
    ]
