# Generated by Django 4.1.5 on 2023-03-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0021_remove_pqrsdf_state_remove_pqrsdfstate_date_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqrsdf',
            name='state_actual',
        ),
        migrations.RemoveField(
            model_name='pqrsdfstate',
            name='date_change',
        ),
        migrations.RemoveField(
            model_name='pqrsdfstate',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pqrsdfstate',
            name='user_change',
        ),
        migrations.AddField(
            model_name='pqrsdf',
            name='state',
            field=models.CharField(choices=[('Radicacion', 'Radicación'), ('Elaboracion', 'Elaboración'), ('Revision', 'Revisión'), ('Finalizado', 'Finalizado')], default='Radicacion', max_length=100, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='pqrsdfstate',
            name='date_input',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Entrada'),
        ),
        migrations.AddField(
            model_name='pqrsdfstate',
            name='date_output',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Salida'),
        ),
        migrations.AddField(
            model_name='pqrsdfstate',
            name='user_change_input',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='Usuario entrada'),
        ),
        migrations.AddField(
            model_name='pqrsdfstate',
            name='user_change_output',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Usuario Salida'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='medium_contact',
            field=models.CharField(blank=True, choices=[('CE', 'Correo electrónico'), ('DC', 'Dirección de correspondencia')], max_length=2, null=True, verbose_name='Medio de contacto'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='type_identification',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('NU', 'NUIP'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PS', 'Pasaporte')], max_length=3, null=True, verbose_name='Tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='pqrsdf',
            name='type_pqrsdf',
            field=models.CharField(choices=[('Peticion', 'Petición'), ('Queja', 'Queja/Reclamo'), ('Solicitud', 'Solicitud de información'), ('Denuncia', 'Denuncia'), ('Sugerencia', 'Sugerencia/Propuesta')], max_length=10, verbose_name='Tipo de PQRSDF'),
        ),
        migrations.AlterField(
            model_name='pqrsdfstate',
            name='id_pqrsdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pqrsdf.pqrsdf'),
        ),
        migrations.DeleteModel(
            name='ResponsePqrsdf',
        ),
    ]
