# Generated by Django 4.1.5 on 2023-03-23 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0023_remove_pqrsdf_state_remove_pqrsdfstate_date_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsdfstate',
            name='id_pqrsdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrsdf.pqrsdf', verbose_name='Id pqrsdf'),
        ),
        migrations.AlterField(
            model_name='pqrsdfstate',
            name='state',
            field=models.IntegerField(choices=[(1, 'Radicación'), (2, 'Elaboración'), (3, 'Revisión'), (4, 'Finalizado')], default=1),
        ),
    ]
