# Generated by Django 4.1.5 on 2023-03-30 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pqrsdf', '0024_alter_pqrsdfstate_id_pqrsdf_alter_pqrsdfstate_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrsdfstate',
            name='date_previous_change',
            field=models.DateTimeField(null=True, verbose_name='Fecha anterior'),
        ),
        migrations.AddField(
            model_name='pqrsdfstate',
            name='user_previous_change',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_previous_change', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Anterior'),
        ),
        migrations.AlterField(
            model_name='pqrsdfstate',
            name='date_change',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Actual'),
        ),
        migrations.AlterField(
            model_name='pqrsdfstate',
            name='user_change',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_change', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Actual'),
        ),
    ]
