# Generated by Django 4.1.5 on 2023-03-30 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pqrsdf', '0025_pqrsdfstate_date_previous_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsdfstate',
            name='date_change',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actual'),
        ),
        migrations.AlterField(
            model_name='pqrsdfstate',
            name='user_change',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_change', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Actual'),
        ),
    ]
