# Generated by Django 4.1.5 on 2023-04-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0026_alter_pqrsdfstate_date_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrsdf',
            name='days_passed',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo transcurrido'),
        ),
    ]
