# Generated by Django 4.1.5 on 2023-04-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsdf', '0028_alter_pqrsdf_days_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsdf',
            name='days_passed',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo transcurrido'),
        ),
    ]
